FROM golang:1.22-alpine

WORKDIR /app

# Install build dependencies
RUN apk add --no-cache git gcc musl-dev

# Install air for hot reload
RUN go install github.com/cosmtrek/air@latest

# Install dependencies
COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 3000

CMD ["air"]