services:
  timescaledb:
    image: timescale-postgis-pg17:latest
    pull_policy: never
    container_name: aquaflow-db
    environment:
      POSTGRES_DB: aquaflowdb
      POSTGRES_USER: aquaflow
      POSTGRES_PASSWORD: changeme
    ports:
      - "5432:5432"
    volumes:
      - /Users/gkalyan/Projects/xOverTime/tidmvp/data/pgdata:/home/postgres/pgdata/data
      # Note: migrations commented out since schema already exists manually
      # - ./db/migrations:/docker-entrypoint-initdb.d
    networks:
      - aquaflow-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aquaflow -d aquaflowdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: aquaflow-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - aquaflow-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/development/Dockerfile.backend
    container_name: aquaflow-api
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://aquaflow:changeme@timescaledb:5432/aquaflowdb?sslmode=disable&search_path=aquaflow
      REDIS_URL: redis://redis:6379
      GIN_MODE: debug
      PORT: 3000
      DB_HOST: timescaledb
      DB_NAME: aquaflowdb
      DB_USER: aquaflow
      DB_PASSWORD: changeme
      DB_PORT: 5432
      DB_SCHEMA: aquaflow
      OLLAMA_HOST: http://ollama:11434
      OLLAMA_MODEL: llama3.2:3b
    volumes:
      - ./backend:/app
      - go_modules:/go/pkg/mod
    networks:
      - aquaflow-network
    depends_on:
      timescaledb:
        condition: service_healthy
      redis:
        condition: service_healthy
      ollama:
        condition: service_healthy
    command: air
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: aquaflow-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@aquaflow.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - aquaflow-network
    restart: unless-stopped
    depends_on:
      - timescaledb

  demo-data-service:
    build: ./demo-data-service
    container_name: demo-data-service
    ports:
      - "8090:8090"
    environment:
      PORT: 8090
    networks:
      - aquaflow-network
    restart: unless-stopped

  etl-workers:
    build: ./etl-workers
    container_name: etl-workers
    environment:
      DATABASE_URL: postgres://aquaflow:changeme@timescaledb:5432/aquaflowdb?sslmode=disable&search_path=aquaflow
    depends_on:
      timescaledb:
        condition: service_healthy
      demo-data-service:
        condition: service_started
    networks:
      - aquaflow-network
    restart: unless-stopped

  etl-jobs-scheduler:
    build: ./etl-jobs-scheduler
    container_name: etl-jobs-scheduler
    environment:
      DATABASE_URL: postgres://aquaflow:changeme@timescaledb:5432/aquaflowdb?sslmode=disable&search_path=aquaflow
      SCHEDULER_CHECK_INTERVAL: 30s
    depends_on:
      timescaledb:
        condition: service_healthy
    networks:
      - aquaflow-network
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: aquaflow-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - aquaflow-network
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "pgrep", "ollama"]
      interval: 15s
      timeout: 5s
      retries: 2
      start_period: 30s



volumes:
  postgres_data:
  redis_data:
  go_modules:
  pgadmin_data:
  ollama_data:

networks:
  aquaflow-network:
    driver: bridge